import yellowCandle from "../../media/yellow_jar_cactus.jpeg";
import whiteCandle from "../../media/white_jar_bathroom.jpeg";
import blueCandle from "../../media/blue_jar_mirror.jpeg";
import greyCandle from "../../media/grey_jar_plant.jpeg";
import pinkCandle from "../../media/two_pink_jars_bed.jpeg";

export const collection = [
  {
    name: "Jar",
    displayImg: yellowCandle,
    color: "bg-slate-100",
    products: [
      {
        type: "Jar",
        id: "whiteJar",
        colour: "white",
        img: whiteCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "yellowJar",
        colour: "yellow",
        img: yellowCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "blueJar",
        colour: "blue",
        img: blueCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "pinkJar",
        colour: "pink",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "purpleJar",
        colour: "Purple",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "redJar",
        colour: "red",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "orangeJar",
        colour: "orange",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "greenJar",
        colour: "green",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "brownJar",
        colour: "brown",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "creamJar",
        colour: "cream",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "blackJar",
        colour: "black",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "greyJar",
        colour: "grey",
        img: greyCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
    ],
  },
  {
    name: "Bubble",
    displayImg: yellowCandle,
    color: "bg-slate-100",
    products: [
      {
        type: "Bubble",
        id: "whiteBubble",
        colour: "white",
        img: whiteCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "yellowBubble",
        colour: "yellow",
        img: yellowCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "blueBubble",
        colour: "blue",
        img: blueCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "pinkBubble",
        colour: "pink",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "purpleBubble",
        colour: "Purple",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "redBubble",
        colour: "red",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "orangeBubble",
        colour: "orange",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "greenBubble",
        colour: "green",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Brown",
        id: "brownBubble",
        colour: "brown",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "creamBubble",
        colour: "cream",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "blackBubble",
        colour: "black",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "greyBubble",
        colour: "grey",
        img: greyCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
    ],
  },
  {
    name: "Wax Melts",
    displayImg: yellowCandle,
    color: "bg-slate-100",
    products: [
      {
        type: "Wax Melt",
        id: "whiteWaxMelt",
        colour: "white",
        img: whiteCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "yellowWaxMelt",
        colour: "yellow",
        img: yellowCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "blueWaxMelt",
        colour: "blue",
        img: blueCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "pinkWaxMelt",
        colour: "pink",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "purpleWaxMelt",
        colour: "Purple",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "redWaxMelt",
        colour: "red",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "orangeWaxMelt",
        colour: "orange",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "greenWaxMelt",
        colour: "green",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "brownWaxMelt",
        colour: "brown",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "creamWaxMelt",
        colour: "cream",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "blackWaxMelt",
        colour: "black",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "greyWaxMelt",
        colour: "grey",
        img: greyCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
    ],
  },
  {
    name: "Wax Melt Gift Set",
    displayImg: yellowCandle,
    color: "bg-slate-100",
    products: [
      {
        type: "Wax Melt Gift Set",
        id: "waxMeltGiftSet",
        colour: "All",
        img: yellowCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
    ],
  },
];
