import yellowCandle from "../../media/yellow_jar_cactus.jpeg";
import whiteCandle from "../../media/white_jar_bathroom.jpeg";
import blueCandle from "../../media/blue_jar_mirror.jpeg";
import pinkCandle from "../../media/two_pink_jars_bed.jpeg";

export const products = [
  {
    name: "Jar",
    displayImg: yellowCandle,
    products: [
      {
        type: "Jar",
        id: "whiteJar",
        colour: "white",
        img: whiteCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "yellowJar",
        colour: "yellow",
        img: yellowCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",

        id: "blueJar",
        colour: "blue",
        img: blueCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
      {
        type: "Jar",
        id: "pinkJar",
        colour: "pink",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 12.0,
      },
    ],
  },
  {
    name: "Bubble",
    displayImg: yellowCandle,
    products: [
      {
        type: "Bubble",
        id: "whiteBubble",
        colour: "white",
        img: whiteCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "yellowBubble",
        colour: "yellow",
        img: yellowCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "blueBubble",
        colour: "blue",
        img: blueCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
      {
        type: "Bubble",
        id: "pinkBubble",
        colour: "pink",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 10.0,
      },
    ],
  },
  {
    name: "Wax Melts",
    displayImg: yellowCandle,
    products: [
      {
        type: "Wax Melt",
        id: "whiteWaxMelt",
        colour: "white",
        img: whiteCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "yellowWaxMelt",
        colour: "yellow",
        img: yellowCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "blueWaxMelt",
        colour: "blue",
        img: blueCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
      {
        type: "Wax Melt",
        id: "pinkWaxMelt",
        colour: "pink",
        img: pinkCandle,
        scents: [
          "Bubblegum",
          "Cedarwood & Jasmine",
          "Baltic Amber & Clove",
          "Fresh Linen",
          "Lime, Basil & Manderin",
          "French Vanilla",
          "Seychelles",
        ],
        price: 3.5,
      },
    ],
  },
];
